include:
  - path: infrastructure/docker/docker-compose-state.yml
  - path: infrastructure/docker/docker-compose-cdc.yml
  - path: infrastructure/docker/docker-compose-obs.yml
  - path: infrastructure/docker/docker-compose-app.yml

networks:
  ledger_network:
    name: ledger_network

volumes:
  caddy_data:
  caddy_config: