receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: basic

  otlphttp/tempo:
    endpoint: http://tempo:4318

  otlphttp/prometheus:
    endpoint: ${env:PROMETHEUS_ENDPOINT}
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlphttp/tempo
        - debug

    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - otlphttp/prometheus

    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
